# Training and Evaluation Settings
model_class: 'binary'         # Model class to use, either 'binary' or 'mlm'
do_train: true                # Train the model
do_eval: true                 # Evaluate the model
do_predict: true              # Predict with the model
num_train_epochs: 3           # Number of epochs to train the model
per_device_train_batch_size: 256  # Batch size for training
per_device_eval_batch_size: 64    # Batch size for evaluation
early_stopping_patience: 10       # Patience for early stopping
early_stop_metric: 'eval_loss'    # Metric for early stopping
early_stop_mode: 'min'            # Mode for early stopping
early_stop_warm_up: 20            # Warm-up period for early stopping
dataloader_drop_last: false       # Drop last batch if smaller than batch size
dataloader_num_workers: 1         # Number of dataloader workers (higher can affect performance)

# Model and Optimizer Settings
learning_rate: 0.00005            # Learning rate for optimizer
weight_decay: 0.01                # Weight decay for optimizer
lr_scheduler_type: 'reduce_lr_on_plateau'  # Learning rate scheduler type
lr_scheduler_kwargs:              # Additional scheduler arguments
  patience: 4                     # Patience for ReduceLROnPlateau scheduler
max_length: 36                    # Maximum input sequence length

# Binary Classification Settings
label_0_cluster_data: 50         # Number of data points for label 0 used in downstream clustering
label_1_cluster_data: 50         # Number of data points for label 1 used in downstream clustering

# MLM Settings
mlm_curriculum_learning: true        # Enable curriculum learning for MLM
mlm_probability: 0.15                # Masking probability for MLM
mlm_curriculum_increase_step: 0.1    # Step size for curriculum learning
mlm_curriculum_max_prob: 0.9         # Maximum masking probability for MLM

# Dataset and File Paths
train_file: '../../data/train_data/whitelab_hemo_data.csv'  # Path to training data
model_path: 'Rostlab/prot_bert_bfd'                         # Path to pretrained model
model_save_path: '../test'                             # Path to save the model
plot_path: '../../plots'                                    # Path to save the plots

# Validation and Test Settings
validation_data_size: 0.1       # Validation dataset size (fraction)
test_data_size: 0.1             # Test dataset size (fraction)
metric_for_best_model: 'loss'   # Metric for selecting best model ['loss', 'accuracy']

# Logging Settings
output_dir: './results'         # Path to checkpoints
logging_dir: './logs'           # Path to logging directory
logging_strategy: 'epoch'       # Logging strategy (set to 'epoch' for this logic)
log_level: 'info'               # Log level
eval_strategy: 'epoch'          # Evaluation strategy (set to 'epoch' for this logic)

# Reproducibility
seed: 42                        # Random seed for reproducibility

# Hardware Settings
use_cpu: true                  # Use CPU for training

# Miscellaneous Settings
classification_weighted_labels: false  # Use weighted labels for classification
ignore_leakage: true                   # Ignore leakage in training data (only if certain)
fast_debug_mode: true                  # Developer mode for pipeline testing
run_verbose: true                      # Show more information during training, like encoding or configs
