# Training and Evaluation Settings
model_class: 'esm_binary'         # Model class to use, either 'binary' or 'mlm'
do_train: true                # Train the model
do_eval: true                 # Evaluate the model
do_predict: true              # Predict with the model
num_train_epochs: 50          # Number of epochs to train the model
per_device_train_batch_size: 32  # Batch size for training
per_device_eval_batch_size: 32    # Batch size for evaluation
early_stopping_patience: 5        # Patience for early stopping
early_stop_metric: 'eval_loss'    # Metric for early stopping
early_stop_mode: 'min'            # Mode for early stopping
early_stop_warm_up: 10            # Warm-up period for early stopping
dataloader_drop_last: false       # Drop last batch if smaller than batch size
dataloader_num_workers: 1         # Number of dataloader workers (higher can affect performance)

# Model and Optimizer Settings
learning_rate: 0.00005            # Learning rate for optimizer
weight_decay: 0.01                # Weight decay for optimizer
lr_scheduler_type: 'reduce_lr_on_plateau'  # Learning rate scheduler type
lr_scheduler_kwargs:              # Additional scheduler arguments
  patience: 4                     # Patience for ReduceLROnPlateau scheduler
max_length: 36                    # Maximum input sequence length

# Binary Classification Settings
label_0_cluster_data: 500         # Number of data points for label 0 used in downstream clustering
label_1_cluster_data: 500         # Number of data points for label 1 used in downstream clustering
loss_function: 'bce'              # Possible Choices ['bce', 'bce_logit_loss']
use_concentration: false          # Use concentration as extra feature [WARNING] U need a prepared train datafile for this

# Dataset and File Paths
train_file: '../../data/train_data/happen_style_unvoted.csv'  # Path to training data
model_path: 'facebook/esm2_t33_650M_UR50D'                               # Path to pretrained model
model_save_path: './feature_BERT'             # Path to save the model
plot_path: './feature_plots'                                   # Path to save the plots

# Validation and Test Settings
validation_data_size: 0.2       # Validation dataset size (fraction)
test_data_size: 0.5             # Test dataset size (fraction)
metric_for_best_model: 'loss'   # Metric for selecting best model ['loss', 'accuracy']

# Logging Settings
output_dir: './results'         # Path to checkpoints
logging_dir: './logs'           # Path to logging directory
logging_strategy: 'epoch'       # Logging strategy (set to 'epoch' for this logic)
log_level: 'info'               # Log level
eval_strategy: 'epoch'          # Evaluation strategy (set to 'epoch' for this logic)

# Reproducibility
seed: 42                        # Random seed for reproducibility

# Hardware Settings
use_cpu: false                  # Use CPU for training

# Miscellaneous Settings
classification_weighted_labels: false  # Use weighted labels for classification
ignore_leakage: false                   # Ignore leakage in training data (only if certain)
run_verbose: true                      # Show more information during training, like encoding or configs
fast_debug_mode: false                  # Developer mode for pipeline testing