training_arguments:
  binary:
    do_train: true
    do_eval: true
    do_predict: true
    output_dir: './results'
    num_train_epochs: 50
    per_device_train_batch_size: 64
    per_device_eval_batch_size: 64
    warmup_steps: 500
    weight_decay: 0.01
    logging_dir: './logs'
    logging_steps: 20
    evaluation_strategy: 'steps'
    log_level: 'info'
    seed: 42
    dataloader_drop_last: false
    dataloader_num_workers: 1
    optim: 'adamw_torch'
    lr_scheduler_type: 'linear'
    learning_rate: 0.00005
  mlm:
    do_train: true
    do_eval: true
    do_predict: true
    output_dir: './results'
    num_train_epochs: 2000
    per_device_train_batch_size: 64
    per_device_eval_batch_size: 64
    warmup_steps: 1000
    weight_decay: 0.01
    logging_dir: './logs'
    logging_steps: 1
    evaluation_strategy: 'steps'
    log_level: 'info'
    seed: 42
    dataloader_drop_last: false
    dataloader_num_workers: 1
    optim: 'adamw_torch'
    lr_scheduler_type: 'linear'
    learning_rate: 0.00005
