training_arguments:
  binary:
    do_train: true
    do_eval: true
    do_predict: true
    output_dir: './results'
    num_train_epochs: 50
    per_device_train_batch_size: 128
    per_device_eval_batch_size: 128
    weight_decay: 0.01
    logging_dir: './logs'
    logging_strategy: 'epoch'
    eval_strategy: 'epoch'
    log_level: 'info'
    seed: 42
    dataloader_drop_last: false
    dataloader_num_workers: 1
    learning_rate: 0.00005
    lro_patience: 4
    lro_factor: 0.1
    lro_min_lr: 0.0000001
    lro_mode: 'min'
    metric_for_best_model : 'loss'
    train_file: '../../data/train_data/whitelab_hemo_data.csv'
    model_path: 'Rostlab/prot_bert_bfd'
    model_save_path: '../binary_BERT'
    plot_path: '../../plots'
    drop_duplicates: true
    ignore_leakage: true
    max_length: 36
    validation_data_size: 0.2
    test_data_size: 0.5
    use_cpu: false
    early_stopping_patience: 10
    early_stop_metric: 'eval_loss'
    early_stop_mode: 'min'
  mlm:
    do_train: true
    do_eval: true
    do_predict: true
    output_dir: './results'
    num_train_epochs: 2000
    per_device_train_batch_size: 64
    per_device_eval_batch_size: 64
    weight_decay: 0.01
    logging_dir: './logs'
    logging_strategy: 'epoch'
    eval_strategy: 'epoch'
    log_level: 'info'
    seed: 42
    dataloader_drop_last: false
    dataloader_num_workers: 1
    learning_rate: 0.00005
    lro_patience: 10
    lro_factor: 0.1
    lro_min_lr: 0.0000001
    lro_mode: 'min'
    metric_for_best_model : 'loss'
    train_file: '../../data/train_data/mlm_train_data.csv'
    model_path: 'Rostlab/prot_bert_bfd'
    model_save_path: '../mlm_BERT'
    plot_path: '../../plots'
    drop_duplicates: true
    ignore_leakage: false
    mlm_probability: 0.15
    max_length: 36
    fast_debug_mode: false
    validation_data_size: 0.2
    test_data_size: 0.5
    use_cpu: false
    early_stopping_patience: 20
    early_stop_metric: 'eval_loss'
    early_stop_mode: 'min'
